### ISSUE TITLE
Setup thruster parameters for thruster manager

### ISSUE THREAD

**Issue by matthewyjiang** [usc-robosub/barracuda-control#2]
in the thruster_manager.yaml configuration file, we need to tell the thruster how much force will be output based on what the input will be. This is because the thruster manager computes the desired thruster input values based on the desired thrust and publishes to each thrusters topic. You need to add a linearly interpolated thruster conversion function that converts from force to input.

Example linear interpolation conversion function:

```
conversion_fcn: custom
conversion_fcn_params:
  input: [0, 1, 2, 3]
  output: [0, 1, 2, 3]
```

Additionally, for this to work in the simulation, the followin issue should be implemented:

https://github.com/usc-robosub/barracuda_description/issues/9
